### Imports

In [3]:
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

In [4]:
DATA_PATH = "/Users/hilsts/Documents/linear-models-benchmark/data/"

df = pd.read_csv(DATA_PATH+"song_data.csv")
df.head()

song_name  song_popularity  song_duration_ms  \
0  Boulevard of Broken Dreams               73            262333   
1                  In The End               66            216933   
2           Seven Nation Army               76            231733   
3                  By The Way               74            216933   
4           How You Remind Me               56            223826   

   acousticness  danceability  energy  instrumentalness  key  liveness  \
0      0.005520         0.496   0.682          0.000029    8    0.0589   
1      0.010300         0.542   0.853          0.000000    3    0.1080   
2      0.008170         0.737   0.463          0.447000    0    0.2550   
3      0.026400         0.451   0.970          0.003550    0    0.1020   
4      0.000954         0.447   0.766          0.000000   10    0.1130   

   loudness  audio_mode  speechiness    tempo  time_signature  audio_valence  
0    -4.095           1       0.0294  167.060               4          0.474  
1    -6.407           0       0.0498  105.256               4          0.370  
2    -7.828           1       0.0792  123.881               4          0.324  
3    -4.938           1       0.1070  122.444               4          0.198  
4    -5.065           1       0.0313  172.011               4          0.574

### Data Preparation


    Toda a preparação de dados será feita no python para deixar apenas a execução dos modelos nas demais linguagens

In [5]:
from sklearn.preprocessing import StandardScaler 


scaler = StandardScaler()


X = df.drop(["song_popularity", "song_name"], axis=1)
scaled_X = scaler.fit_transform(X)
y = df["song_popularity"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
X_train_s, X_test_s, y_train, y_test = train_test_split(scaled_X, y, test_size=0.25)


X_train.to_csv(DATA_PATH+"X_train.csv")
X_test.to_csv(DATA_PATH+"X_test.csv")
y_test.to_csv(DATA_PATH+"y_test.csv")
y_train.to_csv(DATA_PATH+"y_train.csv")

In [6]:
print(X_train)

print(X_train_s)

       song_duration_ms  acousticness  danceability  energy  instrumentalness  \
13867            173600       0.06510         0.797  0.8440          0.000000   
8660             269186       0.42600         0.773  0.8190          0.000000   
2628             255400       0.01330         0.546  0.8780          0.000000   
9259             439480       0.00107         0.747  0.7000          0.043800   
5860             140533       0.90800         0.432  0.2020          0.000000   
...                 ...           ...           ...     ...               ...   
16736            152573       0.15500         0.402  0.5030          0.000002   
10745            120450       0.09890         0.688  0.5110          0.540000   
16991            214552       0.94000         0.258  0.0971          0.000000   
15727            232453       0.05620         0.645  0.7920          0.012100   
18191            225587       0.13400         0.529  0.8170          0.000000   

       key  liveness  loudn

In [23]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
lr = LogisticRegression(fit_intercept=True)

lr.fit(X_train_s, y_train)
pred_s = lr.predict(X_test_s)
print(lr.score(X_test_s, y_test))

lr.fit(X_train, y_train)
pred = lr.predict(X_test)
print(lr.score(X_test, y_test))

print(np.log(np.sqrt(mean_squared_error(y_test, pred_s))))

0.03206625610533022
0.022085368443406243
3.3447610703416917


In [28]:
np.sqrt((y_test - pred_s)**2)

8847      2.0
2726     22.0
15859     0.0
14148    24.0
2658     30.0
         ... 
16106    70.0
7489      6.0
15690     9.0
10207    12.0
17973    40.0
Name: song_popularity, Length: 4709, dtype: float64

In [22]:
test = np.array([10, 15, 40, 40])
pred = np.array([11, 12, 30, 40])

np.log(np.sqrt(mean_squared_error(test, pred)))

1.6570930023362629

67

(1, 244855)

In [8]:
y

array([ 6,  8,  9, 11])

In [9]:
import numpy as np

In [32]:
X.shape

(4, 2)

In [29]:
a = np.arange(21).reshape((3, 7))
a.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [17]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [30]:
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])